In [1]:
!git clone https://github.com/raila-shaukat/multilingual-phishing-detector

Cloning into 'multilingual-phishing-detector'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.

In [2]:
%cd multilingual-phishing-detector

/content/multilingual-phishing-detector

In [3]:
!ls

README.md

In [4]:
from google.colab import files

uploaded = files.upload()

Saving archive.zip to archive.zip

In [5]:
import zipfile
import os

zip_file = "phishingemails.zip"

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall("phishing_dataset")

print(os.listdir("phishing_dataset"))

FileNotFoundError: [Errno 2] No such file or directory: 'phishingemails.zip'

In [6]:
from google.colab import files

uploaded = files.upload()

Saving archive.zip to archive (1).zip

In [7]:
import zipfile
import os

zip_file = "archive.zip"

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall("phishing_dataset")

print("Extracted successfully!")

Extracted successfully!

In [8]:
for root, dirs, files_list in os.walk("phishing_dataset"):
    for file in files_list:
        print(os.path.join(root, file))

phishing_dataset/Phishing_Email.csv

In [13]:
import pandas as pd

file_path = "phishing_dataset/Phishing_Email.csv"

df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (18650, 3)

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [12]:
import os

print(os.listdir("phishing_dataset"))

['Phishing_Email.csv']

In [14]:
import pandas as pd

file_path = "phishing_dataset/Phishing_Email.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

Dataset loaded successfully!
Dataset shape: (18650, 3)

In [15]:
print(df.columns.tolist())

['Unnamed: 0', 'Email Text', 'Email Type']

In [16]:
df.head()

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [17]:
print("Missing values:")
print(df.isnull().sum())

print("\nClass distribution:")
print(df["Email Type"].value_counts())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Missing values:
Unnamed: 0     0
Email Text    16
Email Type     0
dtype: int64

Class distribution:
Email Type
Safe Email        11322
Phishing Email     7328
Name: count, dtype: int64

Duplicate rows:
0

In [18]:
# Remove rows where the email text is missing
df = df.dropna(subset=["Email Text"])

# Remove the unnecessary index column
df = df.drop(columns=["Unnamed: 0"])

# Reset the row numbers
df = df.reset_index(drop=True)

print("Dataset after cleaning:")
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nMissing values:")
print(df.isnull().sum())

Dataset after cleaning:
Shape: (18634, 2)

Columns: ['Email Text', 'Email Type']

Missing values:
Email Text    0
Email Type    0
dtype: int64

In [19]:
print(df["Email Type"].unique())

['Safe Email' 'Phishing Email']